### PR TITLE
Major overhaul: added Definitions, auto target & reference and better error handling

### PR DESCRIPTION
**Pull request by WouterTuinstra**
Hi,

I have changed the following items:
* Removed  init from JsonSchema now using parent init of Directive
* Created a single function replacing the _load_external & _load_internal functions to load the json schema
* Implemented multiple exceptions separately to return better guiding to the error
  * The generated messages are handled by docutils to be printed
* In wide_format new function run, target, section, get_description, definitions, reference have been added
  * The function run has become the new entry point to build the schema
  * The function wrap_in_section has been removed but moved to target and section
* Added documentation with the options that have been added
* Updated the test

A snapshot of the documentation showing how the definitions would render now:
chrome-200828-220854-751

This would include improvements regarding issues: #23, #39 and #40

Greeting

### CODE REVIEW

**Comment by lnoor** [comment]
Hi Wouter,
Just looking at your work when I saw your latest change.

I am delighted with the work you put in.
Especially the improved error handling and the reference to the internal app so that ugly global is gone!
I am still looking into the options you've added.

I haven't tried to run you code yet.
I want to find out:
- if the changes are backward compatible with $$target in particular (scanning the code indicates it would)
- what your new options do, `enable_auto_target` and `enable_auto_reference` sound interesting, could make things a lot easier for simple schemas.
- in particular I want to look at `separate_definitions` since I recently found I needed to use definitions myself :smile:

One thing I like somewhat less is your get_json_data() function.
Although still easily readable I wonder if it is possible to put three different actions in three different files.
But that is a minor gripe compared to all the improvements you made.

I see you are still checking and improving your code.
Once you think it is ready I want to incorporate it in a new release.
Please let me know when you think it is ready.
Leo

**Comment by WouterTuinstra** [comment]
Hi Leo,

Great to hear that you positive about it.

To answer your questions:
* Yes, $$target is backwards compatible the json schema referencing to target should not use `enable_auto_reference `
* Please have a look at the expatiation inside the documentation [auto target and reference]( https://github.com/lnoor/sphinx-jsonschema/blob/b07cab7a5c5d9c98eccd5708009f4f402aba1a38/docs/directive.rst#auto-target-and-reference), if it's not clear let me know
* the `separate_definitions` will initiate a recursive `run` of the content defined in the definition

I can do some functional decomposition inside get_json_data() to improve readability.

I found while working on my schema that I'm also in need of `if` `then` and `else` 
I will let you know when it is ready.

**Comment by lnoor** [comment]
Looks good, thank you.
Before you start on `if`, `then` and `else` I'd like to see how you want to display it.
How you think to fit in in a table.

My suggestion would be something like:
|   |   |
|---|---|
| **if** | cond |
| then | then part |
| else | else part |

**Comment by WouterTuinstra** [comment]
I had the idea to make 3 separate rows for each option one and content will go trough the `_dispatch` function again.

The only thing that I don't like about it now is that it like in the image below it becomes very large
chrome-200831-094232-752

**Comment by lnoor** [comment]
Hence the name WideFormat.
I would have created the same structure.

My schema's do not nest that deeply because I rather agressively factor out (sub)schemas and refer to them.
That makes it easier to talk about those sections in isolation.
It has as its side effect that the nesting is reduced.
My schemas generally describe the properties of a single object, using $ref to define the interior structure.

There is no real solution as this is how the entire layout engine is set up to work.
I hope one day we can choose between mulitple layout engines.

It is in things like these that the software shows its heritage as a personal tool.
It is great to see it is useful to others, even more so that people want to invest time to improve it.

**Comment by lnoor** [comment]
Prepping to create a release.
Correcting a couple of spelling mistakes and improving the documentation (I hope).

I was considering if the option name `lift-description` would be a better name than `separate-description`.
What do you think.

**Comment by WouterTuinstra** [comment]
Sure `lift-description` sounds good as it doesn't completely separate the description but lifts it outside the table.

**Comment by lnoor** [comment]
I've just release v1.16 which includes your PR.
In case you prefer docker: https://hub.docker.com/r/lnoor/sphinx-extended is an image that contains jsonschema.

**Comment by WouterTuinstra** [comment]
@lnoor I'm pretty sure that the `:lift_title:` affects the auto reference and target as it uses the title in an internal dictionary see here: https://github.com/lnoor/sphinx-jsonschema/blob/b8bd6b1e08626bf7c65df1aa8101012bc84445c3/sphinx-jsonschema/wide_format.py#L162

I will have a look

**Pull request merged**
